### ISSUE TITLE
Cannot start GUI and CLI

### ISSUE THREAD

**Issue by joe4dev** [nuweba/faasbenchmark#43]
## GUI

Starting the GUI currently fails due to a missing `debug bool` in `NewGlobalConfig`:

```
# github.com/nuweba/faasbenchmark/tui
tui/main.go:89:40: not enough arguments in call to config.NewGlobalConfig
	have (provider.FaasProvider, string, report.Top)
	want (provider.FaasProvider, string, report.Top, bool)
```
Passing an extra bool value (e.g., true) at [line 89](https://github.com/nuweba/faasbenchmark/blob/master/tui/main.go#L89) fixes the GUI startup.
I can then successfully deploy and undeploy stacks on AWS but I couldn't figure out how to start actual performance tests.

## CLI

The command `go run main.go` immediately returns (with successful exit code). How do I invoke `faasbenchmark list` or `faasbenchmark run`?
![faasbench-cli](https://user-images.githubusercontent.com/8161292/73361340-11916600-42a5-11ea-8120-5a07d5a9112d.gif)

Is `go run main.go` supposed to open an interactive shell or should I pipe faasbenchmark commands into `go run main.go`?
Thanks for clarification!

**Comment by nwb-ilan** [comment]
Thanks for filing the issue!  
We'll be looking into it.  
In the meantime, you can use the cli with:  
`go run main.go run aws Example1`  
Where `Example1` is a test name.  
There are other test stacks you can try as well, for example `IncreasingLoadLvl1`.  
To get a full list of tests and their description you can use:  
`go run main.go list tests`

**Comment by nwb-ilan** [comment]
fixed #44

**Comment by nwb-ilan** [comment]
@joe4dev let me know if you have any other issues

**Comment by joe4dev** [comment]
Thanks for the quick comment and fix.

The tests run nicely on AWS after ensuring the user has the role `AWSLambdaRole` (https://stackoverflow.com/questions/37498124/accessdeniedexception-user-is-not-authorized-to-perform-lambdainvokefunction).

The Google setup has some undocumented conventions:
* Credentials are assumed to be located under `/tmp/.gcloud/faasbenchmark.json`
* The project is assumed to be called `faastest`
* Need to enable "Google Cloud Functions API" and "Cloud Deployment Manager V2 API" in the API & Services Dashboard: https://console.cloud.google.com/apis/dashboard
* Some permission setup is required to fix the error `Error: Required 'deploymentmanager.deployments.list' permission for 'projects/faastest'` (see https://github.com/serverless/serverless-google-cloudfunctions/issues/52)

The Azure credentials setup works as described in the Serverless docs: https://serverless.com/framework/docs/providers/azure/guide/credentials/
However, trying to run any azure test (e.g., `go run main.go run azure Example1`) yields the following error:

```none
2020-01-31T12:17:43.012+0100	INFO	main	config/global.go:46	starting tests
failed reading new stack: failed parsing stack: failed to capture stdout or stderr
exit status 1
```

**Comment by nwb-ilan** [comment]
> Thanks for the quick comment and fix.
> 
> The tests run nicely on AWS after ensuring the user has the role `AWSLambdaRole` (https://stackoverflow.com/questions/37498124/accessdeniedexception-user-is-not-authorized-to-perform-lambdainvokefunction).
> 
> The Google setup has some undocumented conventions:
> 
> * Credentials are assumed to be located under `/tmp/.gcloud/faasbenchmark.json`
> * The project is assumed to be called `faastest`
> * Need to enable "Google Cloud Functions API" and "Cloud Deployment Manager V2 API" in the API & Services Dashboard: https://console.cloud.google.com/apis/dashboard
> * Some permission setup is required to fix the error `Error: Required 'deploymentmanager.deployments.list' permission for 'projects/faastest'` (see [serverless/serverless-google-cloudfunctions#52](https://github.com/serverless/serverless-google-cloudfunctions/issues/52))
> 
> The Azure credentials setup works as described in the Serverless docs: https://serverless.com/framework/docs/providers/azure/guide/credentials/
> However, trying to run any azure test (e.g., `go run main.go run azure Example1`) yields the following error:
> 
> ```
> 2020-01-31T12:17:43.012+0100	INFO	main	config/global.go:46	starting tests
> failed reading new stack: failed parsing stack: failed to capture stdout or stderr
> exit status 1
> ```

Thanks for the detailed report.  
We'll be looking into all of these issues (three of them linked above).
